// import useGoogleSheets from "use-google-sheets";
import Prescription from "./components/Prescription";
import { sampleData } from "./data";
import "./App.css";

// async function fetchGoogleSheet() {
//   // Initialize the sheet - doc ID is the long id in the sheets URL
//   const doc = new GoogleSpreadsheet(
//     "1rceEFM19Ict10k1PGVcV_iqawL55V3YT2VmSLMWFafg"
//   );

//   // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
//   await doc.useServiceAccountAuth({
//     // env var values are copied from service account credentials generated by google
//     // see "Authentication" section in docs for more info
//     client_email: "pranshu.a.11@gmail.com",
//     private_key: "AIzaSyDJbyCLZGBMBfVPp_pyCdwxu5IW148V2KI",
//   });

//   await doc.loadInfo(); // loads document properties and worksheets
//   console.log(doc.title);
// }

function App() {
  const APP_VERSION = "v0.1";
  // const SHEETID = "1rceEFM19Ict10k1PGVcV_iqawL55V3YT2VmSLMWFafg";
  // const APIKEY = "AIzaSyCYdBlnNPHHP31kM7D5-9MW9FeqOHfW_q0";
  // const {
  //   data: _data,
  //   loading,
  //   error,
  // } = useGoogleSheets({
  //   apiKey: APIKEY,
  //   sheetId: SHEETID,
  // });

  // if (loading) {
  //   return <div>Loading...</div>;
  // }

  // if (error) {
  //   return <div>Error! {JSON.stringify(error)}</div>;
  // }

  // if (_data) {
  //   return <div>__data! {JSON.stringify(_data)}</div>;
  // }

  const data = sampleData;

  const complaintsData =
    (data || []).find((el) => el.id === "Complaints")?.data || [];
  const complaints = complaintsData.map((el) => el.Complaints).sort();

  const diagnosisData =
    (data || []).find((el) => el.id === "Diagnosis")?.data || [];
  const diagnosis = diagnosisData.map((el) => el.Diagnosis).sort();

  const medicinesData =
    (data || []).find((el) => el.id === "Medicines")?.data || [];
  const medicines = medicinesData.map((el) => el.Medicines);

  console.log("complaintsData:", complaints);
  console.log("diagnosisData:", diagnosis);
  console.log("medicines:", medicines);

  return (
    <div>
      <Prescription
        APP_VERSION={APP_VERSION}
        data={{ complaints, medicines, diagnosis }}
      />
    </div>
  );
}

export default App;
