export const sampleData = [
  {
    id: "Complaints",
    data: [
      { Complaints: "Pain Abdomen" },
      { Complaints: "Bleeding PV" },
      { Complaints: "Vomittings" },
      { Complaints: "Ghabrahat" },
      { Complaints: "White Discharge" },
      { Complaints: "Prolapse Uterus" },
      { Complaints: "Burning Micturition" },
      { Complaints: "Wants Issue" },
      { Complaints: "Scanty Menses" },
      { Complaints: "Increased Flow" },
      { Complaints: "Chakkar" },
    ],
  },
  {
    id: "Diagnosis",
    data: [
      { Diagnosis: "Early Pregnancy" },
      { Diagnosis: "Full Term Pregnancy" },
      { Diagnosis: "Labour Pains" },
      { Diagnosis: "Tubal Blockage" },
      { Diagnosis: "Anemia" },
      { Diagnosis: "Hypothyrodisim" },
      { Diagnosis: "UTI" },
      { Diagnosis: "Cholilithiasis" },
      { Diagnosis: "PCOD" },
    ],
  },
  {
    id: "Medicines",
    data: [
      { Medicines: "Inj. Sifacee 5000 IU - IM Weekly" },
      { Medicines: "Inj. Lutogen NP - IM Fortnightly" },
      { Medicines: "Inj. Gynonis 250mg - IM On __________" },
      { Medicines: "Inj. Syl - IM / BD" },
      { Medicines: "Tab. Moxikind CV - 625mg - 1BD" },
      { Medicines: "Tab. Zenflox OZ - 1BD" },
      { Medicines: "Tab. Ceffi - 200mg - 1BD" },
      { Medicines: "Tab. Mefkind Spas - 1BD" },
      { Medicines: "Tab. Sinate OD", Frequency: "1BD, 1OD" },
      { Medicines: "Tab. Frevom", Frequency: "1BD, 1OD" },
      { Medicines: "Tab. Zofer - 1BD" },
      { Medicines: "Tab. Eterna - 1BD" },
      { Medicines: "Tab. Avomo - 1BD" },
      { Medicines: "Tab. Flexon - 1BD" },
      { Medicines: "Tab. Pecimol - 1TDS" },
      { Medicines: "Tab. Zocon - 150mg ", Frequency: "Bi Weekly, Weekly" },
      { Medicines: "Tab. Solexyl Plus - 1BD" },
      { Medicines: "Tab. Tranloc E - 1BD" },
      { Medicines: "Tab. Cadisper C - 1TDS" },
      { Medicines: "Tab. Dydrowel - 1BD" },
      { Medicines: "Tab. Cabgolin - 0.5mg - Weekly" },
      { Medicines: "Tab. Letsi 2.5mg - 1 Daily (5 Days)" },
      { Medicines: "Tab. Folvite - 1 Daily" },
      { Medicines: "Tab. Espisol - 75mg - 1 Daily" },
      { Medicines: "Tab. Finecef O - 1BD" },
      { Medicines: "Tab. Cefoxim - 500mg - 1BD" },
      { Medicines: "Tab. Clid VL - Locally" },
      { Medicines: "Tab. Myotin N - 1 Daily" },
      {
        Medicines: "Tab. Thyroxin - Daily",
        Frequency: "25 mcg, 50 mcg, 75 mcg, 100 mcg",
      },
      { Medicines: "Tab. Glimiprex MF - 1BD" },
      { Medicines: "Cap. Vitcofol", Frequency: "1BD, 1OD" },
      { Medicines: "Cap. RRD - 1OD" },
      { Medicines: "Cap. Almox - 500mg - 1TDS" },
      { Medicines: "Cap. Evion - 400mg - 1OD" },
      { Medicines: "Cap. Neurokind LC - 1OD" },
      { Medicines: "Cap. Strone - 1OD" },
      { Medicines: "Syp. Bestozyme - 1TSF - BD" },
      { Medicines: "Syp. Aglozyme - 1TSF - BD" },
      { Medicines: "Syp. Merizyme - 1TSF - BD" },
      { Medicines: "Syp. Hepacef - 2TSF - BD" },
      { Medicines: "Syp. Aptimust - 1TSF - BD" },
      { Medicines: "Syp. Normatone - 1TSF - BD" },
      { Medicines: "Syp. Carecof - 1TSF - BD" },
      { Medicines: "Syp. Becosule - 1TSF - OD" },
      { Medicines: "Liq. Rabemac MPS - 2TSF - BD" },
      { Medicines: "Liq. Cacitron - 1TSF - BD (with glass of water)" },
      { Medicines: "Liq. Laxil - 2TSF - HS" },
    ],
  },
];
